//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSheet
    {
        public int LabSheetID { get; set; }
        public string ConfigFileName { get; set; }
        public string Year { get; set; }
        public string SecretCode { get; set; }
        public int SubsectorTVItemID { get; set; }
        public System.DateTime SampleDate_Local { get; set; }
        public int LabSheetType { get; set; }
        public string FileName { get; set; }
        public System.DateTime FileLastModifiedDate_Local { get; set; }
        public string FileContent { get; set; }
        public string ErrorMessage { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
    }
}
