//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolSourceObservation
    {
        public int PolSourceObservationID { get; set; }
        public int PolSourceSiteTVItemID { get; set; }
        public string ObservationInfo { get; set; }
        public System.DateTime ObservationDate_Local { get; set; }
        public int ContactTVItemID { get; set; }
        public string Observation_ToBeDeleted { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
        public virtual TVItem TVItem1 { get; set; }
    }
}
