//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVFile
    {
        public int TVFileID { get; set; }
        public int TVFileTVItemID { get; set; }
        public string Language { get; set; }
        public int FilePurpose { get; set; }
        public int FileType { get; set; }
        public Nullable<int> DocGenerator { get; set; }
        public Nullable<int> DocGeneratorType { get; set; }
        public string FileDescription { get; set; }
        public int FileSize_kb { get; set; }
        public string FileInfo { get; set; }
        public System.DateTime FileCreatedDate_UTC { get; set; }
        public string ClientFilePath { get; set; }
        public string ServerFileName { get; set; }
        public string ServerFilePath { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
    }
}
